const DATA = [
  {
    "id": 270017,
    "manager": null,
    "t4": "270017",
    "name": "Leticia Wood",
    "role": "Head of Enterprise Apps AU",
    "brand": "Support (Other/Support pillar)",
    "division": "Enterprise Apps",
    "bus_name": "Enterprise Apps AU",
    "status": "A",
    "Manager Name": "",
    "Manager T4": "",
    "job_title": "Head of Enterprise Apps AU",
    "work_nation": "AU - Australia",
    "t3": "308477",
    "T3 Name": "Enterprise Apps AU",
    "Brand Name": "Support (Other/Support pillar)",
    "Division Name": "Enterprise Apps",
    "Discipline Name": "TECHNOLOGY",
    "Region Name": "GLOBAL",
    "Group Name": "FLIGHT CENTRE GROUP",
    "Nation Name": "Australia"
  },
  {
    "id": 109134,
    "manager": 270017,
    "t4": "109134",
    "name": "Ashley Pettit",
    "role": "Technical Business Analyst",
    "brand": "Support (Other/Support pillar)",
    "division": "Enterprise Apps",
    "bus_name": "Enterprise Apps AU",
    "status": "A",
    "Manager Name": "Leticia Wood",
    "Manager T4": "270017",
    "job_title": "Technical Business Analyst",
    "work_nation": "AU - Australia",
    "t3": "308477",
    "T3 Name": "Enterprise Apps AU",
    "Brand Name": "Support (Other/Support pillar)",
    "Division Name": "Enterprise Apps",
    "Discipline Name": "TECHNOLOGY",
    "Region Name": "GLOBAL",
    "Group Name": "FLIGHT CENTRE GROUP",
    "Nation Name": "Australia"
  },
  {
    "id": 113173,
    "manager": 109134,
    "t4": "113173",
    "name": "Elishka Flanigan",
    "role": "Member",
    "brand": "Ignite",
    "division": "Ignite",
    "bus_name": "My Holidays",
    "status": "A",
    "Manager Name": "Ashley Pettit",
    "Manager T4": "109134",
    "job_title": "Member",
    "work_nation": "AU - Australia",
    "t3": "308477",
    "T3 Name": "Enterprise Apps AU",
    "Brand Name": "Ignite",
    "Division Name": "Ignite",
    "Discipline Name": "TECHNOLOGY",
    "Region Name": "GLOBAL",
    "Group Name": "FLIGHT CENTRE GROUP",
    "Nation Name": "Australia"
  },
  {
    "id": 112983,
    "manager": 109134,
    "t4": "112983",
    "name": "Maria Fernando",
    "role": "Member",
    "brand": "Ignite",
    "division": "Ignite",
    "bus_name": "My Holidays",
    "status": "A",
    "Manager Name": "Ashley Pettit",
    "Manager T4": "109134",
    "job_title": "Member",
    "work_nation": "AU - Australia",
    "t3": "308477",
    "T3 Name": "Enterprise Apps AU",
    "Brand Name": "Ignite",
    "Division Name": "Ignite",
    "Discipline Name": "TECHNOLOGY",
    "Region Name": "GLOBAL",
    "Group Name": "FLIGHT CENTRE GROUP",
    "Nation Name": "Australia"
  },
  {
    "id": 112500,
    "manager": 109134,
    "t4": "112500",
    "name": "Jordan Ng",
    "role": "Member",
    "brand": "Ignite",
    "division": "Ignite",
    "bus_name": "My Holidays",
    "status": "A",
    "Manager Name": "Ashley Pettit",
    "Manager T4": "109134",
    "job_title": "Member",
    "work_nation": "AU - Australia",
    "t3": "308477",
    "T3 Name": "Enterprise Apps AU",
    "Brand Name": "Ignite",
    "Division Name": "Ignite",
    "Discipline Name": "TECHNOLOGY",
    "Region Name": "GLOBAL",
    "Group Name": "FLIGHT CENTRE GROUP",
    "Nation Name": "Australia"
  }
];
